name: Alen's Music Site
description: Site about music and drums
author: Alen Siljak
repository: https://github.com/MisterY/music-site

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end